msgbox "SpaceBar Challenge"
msgbox "1"
msgbox "2"
msgbox "3"
msgbox "4"
msgbox "5"
msgbox "6"
msgbox "7"
msgbox "8"
msgbox "9"
msgbox "10"
msgbox "11"
msgbox "12"
msgbox "13"
msgbox "14"
msgbox "15"
inputbox "Alors vous souhaithez refaire en boucle ?"
msgbox "Alors veuillez lancer spacechallengeb.vbs"
msgbox "Au revoir..."